[package]
name = "combine_and_conquer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.1"
bevy_prototype_lyon = "0.6.0"
perlin_noise = "1.0.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
voronoice = "0.2.0"
